name: PAT variable injection into Dockerfile

on:
  push:
    branches:
      - main

jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Read GITHUBPAT
        run: echo "My PAT - ${{secrets.GITHUBPAT}}"

      - uses: action/checkout@v2
      - name: Docker replace ENV variable
        run:
          sed -i "s/<ACTIONGITHUBPAT>/${{secrets.GITHUBPAT}}/g" Dockerfile
        shell: bash