name: PAT variable injection into Dockerfile

on:
  push:
    branches:
      - main

jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Replace placeholder with the PAT secret in the Dockerfile
      - name: Docker replace ENV variable
        run: |
          sed -i "s/<ACTIONGITHUBPAT>/${{secrets.GITHUBPAT}}/g" Dockerfile
        shell: bash
